[package]
name = "pasts_std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
pasts = "0.14.3"
simple_logger = "4.2.0"
chrono = "0.4"